### ISSUE TITLE
Project description is applied to `display-name` annotation instead of `description`

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/opfcli#41]
**Describe the bug**
Project description is applied to `display-name` annotation instead of `description`

**Steps To Reproduce**
1. Run `opfcli create-project -r ../apps testproject testgroup -q x-small -d "My test description."`
2. Check namespace manifests
```yaml
annotations:
        openshift.io/display-name: project-description
```

**Expected behavior**
description should be applied to the `description` annotation instead of `display-name` 
```yaml
annotations:
        openshift.io/description: project-description
```
**Workaround (if any)**
Manually change the manifests

**Comment by larsks** [comment]
The behavior in `opfcli` was simply mirroring the existing behavior in [onboarding.sh](https://github.com/operate-first/apps/blob/master/scripts/onboarding.sh). Is there a specific reason why we're using `display-name` instead of `description` in that script? I guess that's a question for @tumido.

**Comment by tumido** [comment]
Yeah, the reason is quite simple. `display-name` is meant to show in project listings:
![image](https://user-images.githubusercontent.com/7453394/122188303-1fdb2480-ce90-11eb-8e51-e65575a735a6.png)

```sh
$ oc projects    
You have access to the following projects and can switch between them with ' project <projectname>':

    acme-operator - Openshift-ACME Controller
    anonymous
    apicurio-apicurio-registry - Apicurio Registry - High performance, runtime registry for API Designs and Schemas https://www.apicur.io/registry/
    as-pushgateway - AI-Services Push Gateway
    b4mad-minecraft - B4mad: Minecraft
    cnv-testing - dkenigsb cnv testing
    codait-advo - Namespace to complete the Elyra Tutorial
...
```

While `description` is available in project details only:
![image](https://user-images.githubusercontent.com/7453394/122188465-44cf9780-ce90-11eb-9a86-cd174157e6f6.png)

I don't think we ever cared for what appears on project detail page, instead we wanted to have a short description as a display name so we know the namespace purpose.

I don't think we need to store long descriptions per se. We can offer it as an option, sure. In general I think we should insist on `display-name` to be set so we can have a quick guess about the project purpose from the list of projects.

**Comment by tumido** [comment]
That means we probably need to clear the semantic and name the params `display-name` instead of `description` but we should keep using the `display-name` label.
